# Generated by Django 3.1.4 on 2021-03-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1000, unique=True)),
                ('description', models.CharField(max_length=10000)),
                ('image', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
